# Generated by Django 4.2.6 on 2023-10-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40)),
                ('brand', models.CharField(max_length=20)),
                ('flavour', models.CharField(max_length=20)),
                ('extraInformation', models.CharField(max_length=500)),
                ('date', models.DateField()),
            ],
        ),
    ]
